[package]
name = "lox-bytecode-vm"
version = "0.1.0"
authors = ["Yong Le <ygle.he@gmail.com"]
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.68"    # error handling
bytes = "1.3.0"      # helps manage buffers
thiserror = "2.0.12" # error handling
itertools = "0.14.0"
