[package]
name = "lox-bytecode-vm"
version = "0.1.0"
authors = ["Yong Le <ygle.he@gmail.com"]
edition = "2021"
rust-version = "1.80"

[dependencies]
thiserror = "2.0.12"
derive_more = { version = "2", features = ["try_from"] }
slab = "0.4"
